### ISSUE TITLE
Summarize data available from Guttmacher

### ISSUE THREAD

**Issue by mirajshah** [diegogentilepassaro/Abortion-US#7]
[GOAL]
Thoroughly search guttmacher.org for all data, reports that will be useful for this project. Summarize this for the team. Possibly call them up to request more.

**Comment by sgiambra** [comment]
It looks like calling up Guttmacher.org should be our first best strategy to get abortion data. From figure 1 in [this report](https://www.guttmacher.org/article/2017/01/policy-trends-states-2016#fn0) it seems that they have data on abortion restriction laws ready available. Bearak et al (2017) use data from the Guttmacher Institute’s Abortion Provider Census (APC) on abortion clinics by county in 2000, 2011 and 2014.

**Comment by sgiambra** [comment]
Their [datasets page](https://www.guttmacher.org/population-center/datasets) suggests to send an email to popcenter@guttmacher.org for inquires about the data. I will prepare an tentative email tomorrow morning and will share it with the rest of the crew before sending it.

**Comment by diegogentilepassaro** [comment]
Thanks @sgiambra! 

@mmargarita and I already send an email to them on Monday. Let's see if they reply soon.

**Comment by diegogentilepassaro** [comment]
A copy of the email here:

I am working with a team of researchers at Brown University on the impact of reproductive health regulations. We would like to study how access to abortion services and its restrictions may affect outcomes such as health at birth as well as female labor force participation.

We thought you would be the best resource to help us gather information for our project. We are currently compiling a dataset with abortion regulations and the number of facilities providing abortion by state and year since 2000. General information on regulations such as your website tables “targeted regulation of abortion providers” and “overview of state abortion law” would be very helpful. We would like to know if you have this information for previous years and what steps we should follow to obtain access to it.

Let us know if there is anything we could do to facilitate this. We would really appreciate having the opportunity to work on this project with your dataset. We would, of course, acknowledge and thank the Guttmacher Institute for collaboration in our research project, and we could also agree on producing memos of our economics and policy research for your institute.

Yours faithfully,
Margarita Machelett
Phd Candidate, Economics Department
Brown University

**Comment by cravizza** [comment]
I also think they should have data on abortion laws as they pass, but they post only the latest ones (eg. [Abortion laws as of October 1, 2007](https://www.guttmacher.org/state-policy/explore/overview-abortion-laws)). I looked into [archive.org](archive.org) to see if there were older versions of the website stored, but they I couldn't access the screenshots ([they supposedly go from 2001 to 2017](https://web.archive.org/web/*/guttmacher.org)), and the [other ones I found](https://archive.org/search.php?query=guttmacher+overview&sort=-date) only go back until September 2016.

The Guttmacher Institute also has other potentially useful data:
- Clinics providing publicly funded contraceptive services, by county [(here)](https://www.guttmacher.org/report/publicly-funded-contraceptive-services-us-clinics-2015), for 2010 and 2015, at least. This could potentially be useful since the availability of contraceptives could affect abortion prevalence.
- 2008 Abortion Patient Survey (APS), which is [available upon request](https://www.guttmacher.org/population-center/datasets). It's only 9,493 abortion patients, is at the state level (state of residency, state where abortion facility is located). Includes variables such as: travel distances (lives in same zipcode, 1 mile, 2 miles, 3 miles, 400miles or more), an indicator for wanted pregnancy, and demographics. This type of data could be useful for robustness checks, or to test assumptions or mechanisms in place (but on 2008).

**Comment by sgiambra** [comment]
Thanks guys! I propose to fill in this [request form](https://www.guttmacher.org/sites/default/files/page_files/pu-datasetform.pdf) and send it by tonight's meeting so that we start getting the four rounds of Abortion Patient Survey (APS).

**Comment by diegogentilepassaro** [comment]
Grande @sgiambra! I've printed it and will fill it now.

**Comment by mmargarita** [comment]
Hi guys, I am checking the datasets from the institute again before we email them. I would like to check with you if we really want to request the "2009 National Survey of Reproductive and Contraceptive Knowledge". 

Since we want to maximize the probability of obtaining the data, maybe we could not ask for this survey and request it later once we are sure we will use it. My concern is  that if we ask for everything, they may not take us seriously. Will do whatever you think is best. 

Thanks :)

**Comment by mmargarita** [comment]
Due to lack of reply, I just send an email requesting the 2010 clinic survey. Once we make more progress, we can request the other datasets.

**Comment by mirajshah** [comment]
@mmargarita the next task is to follow up with Guttmacher about the two surveys which they did not send across.
